/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yscall_ndksample_JNIUtils */

#ifndef _Included_com_yscall_ndksample_JNIUtils
#define _Included_com_yscall_ndksample_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yscall_ndksample_JNIUtils
 * Method:    getHelloString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yscall_ndksample_JNIUtils_getHelloString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
